LpFilt = designfilt('lowpassfir', ...
                    'PassbandFrequency',13000000, ...
                    'StopbandFrequency',24000000, ...
                    'PassbandRipple',0.1, ...
                    'StopbandAttenuation',60, ...
                    'SampleRate',52000000, ...
                    'DesignMethod','kaiserwin');
figure(1);fvtool(LpFilt);

