clear all;
close all;
clc;


LpFilt = designfilt('lowpassfir', ...
                    'PassbandFrequency',6, ...
                    'StopbandFrequency',30, ...
                    'PassbandRipple',0.1, ...
                    'StopbandAttenuation',44, ...
                    'SampleRate',100, ...
                    'DesignMethod','kaiserwin');
figure(1);fvtool(LpFilt);